### ISSUE TITLE
Guide on how to configure IDE to work well with RiotTS split of ts and html files

### ISSUE THREAD

**Issue by web3d0** [nippur72/RiotTS#14]
Eg, for Webstorm IDE. Does ///reference need to be at the top of every .ts file? How is HTML inspection configured to remove multiple errors from html file?

How can the project be set up to allow Live Edit?

Also, app.js needs to be loaded at the bottom of the body, not within the head, or the browser won't have seen the tag yet for Riot to be able to perform the replacement.

**Comment by web3d0** [comment]
Live Edit works in Webstorm 10, but not 11 EAP Beta. I have filed a bug for this, currently work around the HTML errors by turning them off, and am including ////reference in every TS file. Better ideas? Still trying to figure out a way to update the template string during runtime.

**Comment by nippur72** [comment]
Regarding the `/// <reference` issue: check if WebStorm does support `tsconfig.json` (I guess it does). If it does, move your `/// <reference` to the `tsconfig.json` file.

In the VS IDE, references are usually grouped in the file `_references.ts` which is also used to establish concatenation priority when producing a single .js file output. But I guess it's a peculiar thing to VS.

Regarding where to place `app.js`: you might want to mount tags after the `onload` event (or something similar):

```
window.onload = function() 
{   
   Riot.registerAll();
   riot.mount('*');
}
```

**Comment by web3d0** [comment]
Still having trouble with when app.js runs. If I use the window.onload approach, I get "Error: Invalid value for <rect> attribute x="{time%280}"" - but if I call it manually from the console then it loads without error. I think the reason for this is the @template, so I'll try moving them off to html files.

**Comment by web3d0** [comment]
I'm not able to mount this with any permutation of window.onload, setTimeout or other approach other than typing riot.mount("*") manually in the console. It still works even with the error, but there is a dump about how the SVG has a bad value. So make a quick index.html mounting this box.ts (box.js) tag to see the problem. No difference if the template is moved to a separate HTML file.

Error is:

```
Error: Invalid value for <rect> attribute x="{time%280}"
  Tag   
  mountTo   
  pushTags  
  each  
  riot.mount    
  (anonymous function)  
  done  
  compileScripts    
  riot.compile  
  riot.mount    
  whoo
```

Code is:

```
@template(`<box>
    <div style="position:absolute; top:50px; left:100px; background-color: deepskyblue;">
        timerimerddsity: { time }<br>
        <svg>
            <rect x="{time%280}" y="20" width="25" height="75" rx="20"
                  style="fill:#ff0000; stroke:#000000;stroke-width:2px;" />
            <rect x="110" y="60" width="75" height="25" rx="40"
                  style="fill:#0000ff; stroke:#000000; stroke-width:2px;
        fill-opacity:0.7;" />
        </svg>
        <br>
        <div each="{el in mylist}">
            iterating {el}<br>Bloop</div>
    </div>
</box>`)

class Box extends Riot.Element {
    time:number = 0;
    timerHandle:number;
    mylist = ["one", "two", "three"];
    constructor(opts) {
        super();
        this.time = opts.time || 0;
        this.timerHandle = setInterval(() => this.ticks(), 10);
    }
    ticks() {
        this.time += 0.1;
        this.update();  // refreshes the element
    }
    unmounted() {
        clearInterval(this.timerHandle);
    }
}

function whoo() {
    console.log("ok");
    riot.mount("*");
}

setTimeout(whoo, 1000);
Riot.registerAll();
```

**Comment by nippur72** [comment]
I'm looking into this right now, I write asap

**Comment by nippur72** [comment]
Okay, it doesn't depend on RiotTS, it's a riot bug, it seem that it doesn't like SVG tags.

See this [riot issue](https://github.com/riot/riot/issues/853).

**Comment by web3d0** [comment]
OK, sorry for thinking it was in @template - that was how far I was able to trace it since I wasn't getting stack dumps in Webstorm. Chrome had stack traces but no call by call variables to figure out where the issue was, so thank you for following through to that riot issue!
