### ISSUE TITLE
@template creates a run-time access to tag component. Compile time inclusion?

### ISSUE THREAD

**Issue by web3d0** [nippur72/RiotTS#15]
I expected the @template reference to a html file to be the same as an inline string except that the HTML file would be editable in an IDE. Instead, it is doing a XMLHttpRequest to build the tag file at runtime, and has a notation to make it asynchronous to avoid the deprecation message.

It seems to me that the Typescript compile stage is where the HTML file could be included into the generated JS file. The result would then be compiled at run-time through RiotJS, and then wired up by RiotTS. I can't find a generic file import, but Typescript does have modules.

So the HTML file could pretend to be JS files with something like ()={/\* wrappers? Another option would be to use the Riot tag compiler as part of a grunt/gasp task?

**Comment by nippur72** [comment]
Check the latest RiotTS, it supports a template-cache that can be build simply by a grunt task. 

The idea is to use HttpRequests during the development phase, but switch to preloaded javascript when you go in production.

See https://github.com/nippur72/RiotTS#concat (and tell me if it's enough clear).

P.S. this technique will be also useful with the new riot (2.3) because expressions of compiled expressions. So I think we will have a bigger grunt task that moves tag from HTML, compiles them and put all in a javascript file.

**Comment by web3d0** [comment]
The concatenation yes, but the cached templates is complex and seems to clean up after the problem rather than solving the problem. Even for development phase, there is still a compiler pass which could do that merging, or the riot tag compiler could be slightly improved.

After all, a build time script is pretty much just a bash script going "for blah in *; do cat $blah.html $blah.ts | tsc > $blah.js; done"... This isn't a problem that the original Riot has, so it seems a high price to pay just to split a tag file in half.

**Comment by nippur72** [comment]
As I'm going to add the new 2.3 features (compiled expressions) do you have any specific suggestion how it could be improved? 

The current grunt task is not bad IMO, perhaps a bit annoying to setup. But it's a one-time thing, once it's configured you don't have to mess with it.

**Comment by web3d0** [comment]
No suggestions. It's there, so may as well use it. It wouldn't be a Typescript version of Riot if it wasn't what Riot was. :)

**Comment by nippur72** [comment]
Closing this as the new template-cache and grunt task can avoid the GET request.

**Comment by nippur72** [comment]
@web3d0 if you are still interested in this issue, the new RiotTS v0.0.19 supports pre-compiled tags in place of the old "template cache".

**Comment by web3d0** [comment]
@nippur72 Thanks, yes still interested.

**Comment by nippur72** [comment]
Have a look at [README.md#precompiled](https://github.com/nippur72/RiotTS/blob/master/README.md#precompiled), there is a grunt task that does all the precompilation work. 

Let me know if you find it difficult to setup as it's my first grunt-plugin that I write.
