### ISSUE TITLE
Access HTML element by id in the ts file

### ISSUE THREAD

**Issue by visopsys** [nippur72/RiotTS#16]
Do you know how I can access an element in HTML file in ts file. Suppose I have template file 

```
<hellow-world>
   <div id="contentFrame"></div>
</hellow-world>
```

and I have hello_world.ts:

```
@template("hello-world.html")
class HelloWorld extends Riot.Element {
  ...
}
```

How do I access the `<div>` tag in the .ts file? Native javascript riot allows something like `var content=this.contentFrame` but this is not allowed in typescript class.

**Comment by nippur72** [comment]
since you have used `id` in your `<div>` you can simply reference it:

``` TypeScript
@template("hello-world.html")
class HelloWorld extends Riot.Element {
    contentFrame: HTMLElement;  // same name as in "id" (or "name")
    someFunction()
    {
        this.contentFrame.innerHTML = "blah";
    }   
}
```

of course for other elements like `<input>` you can use `HTMLInputElement` ecc...

**Comment by visopsys** [comment]
I got it. It turns out that I had wrong variable name and they did not match. I thought it did not work in typescript.
