### ISSUE TITLE
Hello World example?

### ISSUE THREAD

**Issue by yissachar** [nippur72/RiotTS#19]
This looks like a very interesting project and I'd love to play with it, but I'm having issues getting a Hello World working just from the readme. Is there a simple self-contained project out there that contains some basic RiotTS code, as well as step-by-step instructions on how to run it?

**Comment by nippur72** [comment]
I've just written one here: 

https://github.com/nippur72/RiotTS-helloworld

(or see it: http://nippur72.github.io/RiotTS-helloworld/)

it's made in plain command-line style (tsconfig.json) because wasn't sure if you had Visual Studio or not.

Write here if you have questions or need assistance :-)

**Comment by yissachar** [comment]
Wow, thanks for the speedy response - that's exactly what I needed. I'm not using Visual Studio so tconfig,json is perfect for me. I've got a few other questions, but I'll create new issues for them to keep things clean.

Thanks!
