### ISSUE TITLE
npm package and Typescript 2.0 module issue

### ISSUE THREAD

**Issue by sandrokeil** [nippur72/RiotTS#36]
I'm playing around with the [riot-ts npm package](https://www.npmjs.com/package/riot-typescript) and Typescript 2.0, but the riot module is not found.

Can you update your [RiotTS-helloworld](https://github.com/nippur72/RiotTS-helloworld) example with only npm and without bower please? My `tsconfig.json` looks like this:

```
{
    "files": [
        "./node_modules/riot-ts/index.d.ts",
        "src/main.ts"
    ],
    "compilerOptions": {
        "noImplicitAny": false,
        "target": "es2015",
        "experimentalDecorators": true,
        "sourceMap": true,
        "jsx": "preserve"
    }
}
```

I've tried different import definitions for the timer example, but I got different errors. Have you any ideas?

**Comment by sandrokeil** [comment]
If you are familiar with [Docker](https://www.docker.com/), you can use my [Typescript 2.0 Docker Image](https://github.com/sandrokeil/docker-files/tree/master/typescript).

```
$ docker run --rm -it --volume $(pwd):/app sandrokeil/typescript [ gulp | tsc | bower | node | typings |webpack ]
```

**Comment by nippur72** [comment]
btw `riot-ts` is not mine, I had to publish it as `riot-typescript`. Please read my comment in #30.

**Comment by sandrokeil** [comment]
The new version 1.0.10 works like a charm. :+1:
