### ISSUE TITLE
Not available in bower repository

### ISSUE THREAD

**Issue by mr-moon** [nippur72/RiotTS#4]
Just tried to install via bower, and it (riot-ts) wasn't found. Looked over http://bower.io/search/?q=riot same thing.

**Comment by nippur72** [comment]
looks like I forgot to register, in the while, install via 

```
bower install nippur72/RiotTS
```

(it's always updated)

**Comment by nippur72** [comment]
and now available as 

```
bower install riot-ts
```

thank you very much!
