### ISSUE TITLE
Wrong comment on element tags.

### ISSUE THREAD

**Issue by alesch** [nippur72/RiotTS#6]
Hi,

The readme has a code snippet with the following comment:
`<!-- notice there is no <my-element> tag -->`, but there is one.

Thanks for RiotTS!

**Comment by nippur72** [comment]
Good catch, thanks!

Previously the RiotTS syntax was without the surrounding element, but you had to specify the tag name separately. Later the syntax changed but I missed to update the README, so many thanks.
